#ifndef __CORE_STATS_H__
#define __CORE_STATS_H__

/* Statistics map counter indices */
enum stat_counter {
    STAT_TOTAL_PACKETS = 0,
    STAT_INGRESS_PACKETS,
    STAT_EGRESS_PACKETS,
    STAT_ALLOWED_PACKETS,
    STAT_DROPPED_PACKETS,
    STAT_TCP_PACKETS,
    STAT_UDP_PACKETS,
    STAT_ICMP_PACKETS,
    STAT_OTHER_PACKETS,
    STAT_DROPPED_UNSOLICITED,
    STAT_DROPPED_RULE,
    STAT_DROPPED_MALFORMED,
    STAT_CONN_NEW,
    STAT_CONN_ESTABLISHED,
    STAT_CONN_CLOSED,
    STAT_CONN_TIMEOUT,
    STAT_MAX_COUNTERS,
};

#endif /* __CORE_STATS_H__ */
