# ==========================================================
#         eBPF / XDP Minimalist Firewall Configuration
# ==========================================================

interface: incus-protect

global:
  log_level: info
  stats_interval_sec: 1
  ringbuf_poll_timeout_ms: 100
  default_policy: pass
