#ifndef __PROTOCOLS_ICMP_TYPES_H__
#define __PROTOCOLS_ICMP_TYPES_H__

#define ICMP_TYPE_ECHO_REPLY    0
#define ICMP_TYPE_DEST_UNREACH  3
#define ICMP_TYPE_ECHO_REQUEST  8
#define ICMP_TYPE_TIME_EXCEEDED 11

#endif /* __PROTOCOLS_ICMP_TYPES_H__ */
